modules:
  health:
    class: modai.modules.health.simple_health_module.SimpleHealthModule
  chat_router:
    class: modai.modules.chat.web_chat_router.ChatWebModule
    config:
      clients:
        openai: chat_openai
    module_dependencies:
      chat_openai: chat_openai
  chat_openai:
    class: modai.modules.chat.openai_raw_chat.OpenAILLMChatModule
    module_dependencies:
      llm_provider_module: openai_model_provider
  model_provider_store:
    class: modai.modules.model_provider_store.sql_model_provider_store.SQLAlchemyModelProviderStore
    config:
      database_url: "sqlite:///./llm.db"
      echo: false
  openai_model_provider:
    class: modai.modules.model_provider.openai_provider.OpenAIProviderModule
    module_dependencies:
      llm_provider_store: "model_provider_store"
  central_model_provider_router:
    class: modai.modules.model_provider.central_router.CentralModelProviderRouter
    module_dependencies:
      openai_provider: "openai_model_provider"
  user_store:
    class: modai.modules.user_store.sql_model_user_store.SQLAlchemyUserStore
    config:
      database_url: "sqlite:///./user_store.db"
      echo: false
  user_settings_store:
    class: modai.modules.user_settings_store.sqlalchemy_user_settings_store.SQLAlchemyUserSettingsStore
    config:
      database_url: "sqlite:///./user_settings.db"
      echo: false
  session:
    class: modai.modules.session.jwt_session_module.JwtSessionModule
    config:
      jwt_secret: ${JWT_SECRET}
      jwt_algorithm: "HS256"
      jwt_expiration_hours: 24
      cookie_secure: true
  authentication:
    class: modai.modules.authentication.password_authentication_module.PasswordAuthenticationModule
    module_dependencies:
      session: "session"
      user_store: "user_store"
  user:
    class: modai.modules.user.simple_user_module.SimpleUserModule
    module_dependencies:
      session: "session"
      user_store: "user_store"
  user_settings:
    class: modai.modules.user_settings.simple_user_settings_module.SimpleUserSettingsModule
    module_dependencies:
      session: "session"
      user_settings_store: "user_settings_store"
